### ISSUE TITLE
Fix the segfault in `depending-on`/`cobrand`

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/trying.cob#1]
```
Attempt to reference unallocated memory (Signal SIGSEGV)
Abnormal termination - File contents may be incorrect
```

Not sure what it's due to.
@rightfold says it's better to pass parameters explicitly. I'll try that later.

**Comment by no-longer-on-githu-b** [comment]
Use GDB.

**Comment by vendethiel** [comment]
but I don't want to touch ASM :(

**Comment by no-longer-on-githu-b** [comment]
I also don't want to do a lot of things I have to do but I have to do them anyway.

**Comment by vendethiel** [comment]
Actually, `cobc cobrand.cob -g && cobc -x -g depending-on.cob && lldb ./depending-on` gives me good stuff.

**Comment by no-longer-on-githu-b** [comment]
Excellent.

**Comment by vendethiel** [comment]
670fc4146728d23d1759c998faa53ea3960f81ad
